'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import type { z } from 'zod';

import { complianceEventSchema, obligationSchema, today } from '@/lib/domain/compliance';
import { createClient } from '@/lib/supabase/server';

export type FormState =
  | { ok: true }
  | { ok: false; message: string; fieldErrors?: Record<string, string> }
  | null;

function toFieldErrors(error: z.ZodError): Record<string, string> {
  const out: Record<string, string> = {};
  for (const issue of error.issues) {
    const key = String(issue.path[0] ?? '_');
    out[key] ??= issue.message;
  }
  return out;
}

function revalidateCompliance(obligationId?: string) {
  revalidatePath('/compliance');
  revalidatePath('/compliance/register');
  if (obligationId) revalidatePath(`/compliance/obligations/${obligationId}`);
}

/**
 * All of these write through the user's own session, so RLS decides what is permitted.
 * None of them accepts or sets organization_id -- the BEFORE INSERT trigger assigns it.
 *
 * None of them writes to compliance_events for scheduling purposes either: the calendar
 * is generated by the database trigger on the obligation, so there is exactly one place
 * where a due date can come into existence.
 */
export async function saveObligation(_prev: FormState, formData: FormData): Promise<FormState> {
  const id = String(formData.get('id') ?? '') || null;
  const parsed = obligationSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return {
      ok: false,
      message: 'Check the highlighted fields.',
      fieldErrors: toFieldErrors(parsed.error),
    };
  }

  const supabase = await createClient();
  const { data, error } = id
    ? await supabase
        .from('compliance_obligations')
        .update(parsed.data as never)
        .eq('id', id)
        .select('id')
        .single()
    : await supabase
        .from('compliance_obligations')
        .insert(parsed.data as never)
        .select('id')
        .single();

  if (error) return { ok: false, message: error.message };

  revalidateCompliance(data.id);
  redirect(`/compliance/obligations/${data.id}`);
}

export async function deleteObligation(id: string) {
  const supabase = await createClient();
  const { error } = await supabase.from('compliance_obligations').delete().eq('id', id);
  if (error) throw new Error(error.message);

  revalidateCompliance();
  redirect('/compliance/register');
}

/**
 * Records the outcome of one calendar entry.
 *
 * Completing an instance of a recurring obligation asks the generator to top the calendar
 * back up afterwards. The generation window is measured from today, so without this a
 * client who works steadily through their calendar would eventually reach the end of it.
 */
export async function saveComplianceEvent(
  eventId: string,
  obligationId: string,
  _prev: FormState,
  formData: FormData,
): Promise<FormState> {
  const parsed = complianceEventSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return {
      ok: false,
      message: 'Check the highlighted fields.',
      fieldErrors: toFieldErrors(parsed.error),
    };
  }

  const supabase = await createClient();
  const { error } = await supabase
    .from('compliance_events')
    .update(parsed.data as never)
    .eq('id', eventId);

  if (error) return { ok: false, message: error.message };

  if (parsed.data.completed_date) {
    await supabase.rpc('generate_compliance_events', { p_obligation_id: obligationId });
  }

  revalidateCompliance(obligationId);
  return { ok: true };
}

/**
 * The one-click completion from the calendar, dated today.
 *
 * Today is an actual, not an estimate: it is the date the user is telling us the work was
 * done. Anything else -- back-dating to the due date, say -- would be the system inventing
 * a completion date, and this is a record a regulator may read.
 */
export async function completeComplianceEvent(
  eventId: string,
  obligationId: string,
  completedBy: string | null,
): Promise<{ ok: boolean; message?: string }> {
  const supabase = await createClient();
  const { error } = await supabase
    .from('compliance_events')
    .update({
      status: 'Compliant',
      completed_date: today(),
      completed_by: completedBy,
    })
    .eq('id', eventId);

  if (error) return { ok: false, message: error.message };

  await supabase.rpc('generate_compliance_events', { p_obligation_id: obligationId });

  revalidateCompliance(obligationId);
  return { ok: true };
}

/** Reverses a completion, for the mis-click. The entry returns to its dated state. */
export async function reopenComplianceEvent(
  eventId: string,
  obligationId: string,
): Promise<{ ok: boolean; message?: string }> {
  const supabase = await createClient();
  const { error } = await supabase
    .from('compliance_events')
    .update({
      status: 'Not Started',
      completed_date: null,
      completed_by: null,
    })
    .eq('id', eventId);

  if (error) return { ok: false, message: error.message };

  revalidateCompliance(obligationId);
  return { ok: true };
}

/**
 * Extends the calendar for every obligation in the caller's organisation.
 *
 * Idempotent by construction -- the generator cannot duplicate an existing date -- so
 * running it twice is harmless and running it never is the only way to get it wrong.
 */
export async function refreshComplianceCalendar(): Promise<{
  ok: boolean;
  created?: number;
  message?: string;
}> {
  const supabase = await createClient();
  const { data, error } = await supabase.rpc('refresh_compliance_calendar');

  if (error) return { ok: false, message: error.message };

  revalidateCompliance();
  return { ok: true, created: data ?? 0 };
}
